Catalog1/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace Catalog1.Models
{
    public class Product
    {
        [Key]
        public int ProductID { get; set; }

        [DisplayName("Product Name")]
        public string Name { get; set; }

        public int Quantity { get; set; }

        [DisplayName("Order Max Qty")]
        public int OrderMaximumQuantity { get; set; }

        public Decimal Price { get; set; }

        public string Description { get; set; }

        [DisplayName("Small Image")]
        public string ImageSmall { get; set; }

        [DisplayName("Large Image")]
        public string ImageLarge { get; set; }

        [DisplayName("Price Modifier")]
        public Decimal PriceModifier { get; set; }

        public virtual ICollection<ProductReview> Reviews { get; set; }

        [NotMapped]
        public int AverageReview
        {
            get
            {
                int avg = 0;

                if (Reviews != null && Reviews.Count != 0)
                {
                    double? avgdetail = Reviews.Average<ProductReview>(x => x.Rating);
                    avg = (int)Math.Round(avgdetail.Value, 0);
                }

                return avg;
            }
        }
    }
}

Catalog1/Controllers/CartItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Catalog1.Models;

namespace Catalog1.Controllers
{
    public class CartItemsController : Controller
    {
        private WidgetModel db = new WidgetModel();

        // GET: CartItems
        [SiteMap]
        public ActionResult Index()
        {
            Repository repository = new Repository(db);

            var cart = repository.GetCartByName(User.Identity.Name);

            return View(cart.First().Carts.ToList());
        }

        // GET: CartItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = db.CartItems.Find(id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            return View(cartItem);
        }

        // GET: CartItems/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CartItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CartItemID,Name,Quantity,Price")] 
            CartItem cartItem)
        {
            if (ModelState.IsValid)
            {
                db.CartItems.Add(cartItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cartItem);
        }

        // GET: CartItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = db.CartItems.Find(id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            return View(cartItem);
        }

        // POST: CartItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "CartItemID,Name,Quantity,Price")] CartItem cartItem)
        public ActionResult Edit( int CartItemID, int Quantity)
        {
            var cartItem = db.CartItems.Find(CartItemID);
            
            if (Quantity >= 0)
            {
                cartItem.Quantity = Quantity;
            }
            if (ModelState.IsValid)
            {
                db.Entry(cartItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cartItem);
        }

        // GET: CartItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = db.CartItems.Find(id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            return View(cartItem);
        }

        // POST: CartItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CartItem cartItem = db.CartItems.Find(id);
            db.CartItems.Remove(cartItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Catalog1/Controllers/ProductController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Catalog1.Models;
using System.Collections.Generic;
using System.Net;

namespace Catalog1.Controllers
{
    public class ProductController : Controller
    {
        //WidgetModel db = new WidgetModel();

        Repository repository;

        // Normal program operation
        public ProductController()
        {
            repository = new Repository(new WidgetModel());
        }
        // Testing
        public ProductController(Repository repo)
        {
            repository = repo;
        }

        // GET: Product
        [SiteMap]
        public ActionResult Index()
        {
            ViewBag.UserName = "Lord User";

            var products = repository.GetAllProducts();

            return View(products);
        }
        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                //RedirectToAction("Index");
            }
            Product product = repository.FindByID(id);

            if (product == null)
            {
                return HttpNotFound();
            }

            return View(product);
        }

        [Authorize]
        public ActionResult ShoppingCart(int? productID, int amount = 0)
        {
            Cart userShoppingCart;
            
            userShoppingCart = repository.FindOrCreateCart(User.Identity.Name);

            // Add a Shopping Cart Item (CartItems)
            repository.AddShoppingCart(productID, amount, userShoppingCart);
            
            //ViewBag.PriceTotal = userShoppingCart.PriceTotal;
            
            return View(userShoppingCart);
        }
        [Authorize]
        public ActionResult Purchase()
        {
            repository.PurchaseCart(User.Identity.Name);
            return View();
        }

        

        //[HttpGet]
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = repository.FindByID(id);

            if (product == null)
            {
                return HttpNotFound();
            }

            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                repository.UpdateProduct(product);
                return RedirectToAction("Index");
            }
            return View(product);
        }
    }
}

Catalog1/Controllers/ProductReviewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Catalog1.Models;

namespace Catalog1.Controllers
{
    public class ProductReviewsController : Controller
    {
        private WidgetModel db = new WidgetModel();

        // GET: ProductReviews
        [SiteMap]
        public ActionResult Index()
        {
            return View(db.ProductReviews.ToList());
        }

        // GET: ProductReviews/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductReview productReview = db.ProductReviews.Find(id);
            if (productReview == null)
            {
                return HttpNotFound();
            }
            return View(productReview);
        }

        // GET: ProductReviews/Create
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.ProductID = id;

            return View(new ProductReview() { TimeStamp = DateTime.Now });
        }

        // POST: ProductReviews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(
            [Bind(Include = "ProductReviewID,IsApproved,Title,ReviewText,Rating,TimeStamp")] 
            ProductReview productReview,
            int ProductID)
        {
            if (ModelState.IsValid)
            {
                var product = db.Products.Find(ProductID);
                product.Reviews.Add(productReview);

                db.ProductReviews.Add(productReview);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productReview);
        }

        // GET: ProductReviews/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductReview productReview = db.ProductReviews.Find(id);
            if (productReview == null)
            {
                return HttpNotFound();
            }
            return View(productReview);
        }

        // POST: ProductReviews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductReviewID,IsApproved,Title,ReviewText,Rating,TimeStamp")] ProductReview productReview)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productReview).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(productReview);
        }

        // GET: ProductReviews/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductReview productReview = db.ProductReviews.Find(id);
            if (productReview == null)
            {
                return HttpNotFound();
            }
            return View(productReview);
        }

        // POST: ProductReviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductReview productReview = db.ProductReviews.Find(id);
            db.ProductReviews.Remove(productReview);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Catalog1/Views/Product/Detail.cshtml
@model Catalog1.Models.Product

@{
    ViewBag.Title = "Product details";
}
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <div class="col-md-3">
                <p class="lead">Shop Name</p>
                <div class="list-group">
                    <a href="#" class="list-group-item active">Category 1</a>
                    <a href="#" class="list-group-item">Category 2</a>
                    <a href="#" class="list-group-item">Category 3</a>
                </div>
            </div>

            <div class="col-md-9">

                <div class="thumbnail">
                    <img class="img-responsive" src="@Html.DisplayFor(model => model.ImageLarge)" alt="">
                    <div class="caption-full">
                        <h4 class="pull-right">$@Html.DisplayFor(model => model.Price)</h4>
                        <h4><a href="#">@Html.DisplayFor(model => model.Name)</a>
                        </h4>
                        <p>@Html.DisplayFor(model => model.Description)</p>
                    </div>
                    <div class="ratings">
                        <p class="pull-right">@Html.DisplayFor(model => model.Quantity) in stock</p>
                        <p>
                            @Html.Partial("DisplayStarRating")
                            @Model.AverageReview stars
                        </p>
                    </div>
                    @using (Html.BeginForm("ShoppingCart", "Product"))
                    {
                        <h4>Qty:</h4>
                        @Html.HiddenFor(model => model.ProductID, new { id = "productID" })
                        @Html.TextBox("amount", 1)
                        <input type="submit" value="Add to Cart" class="btn btn-default"/>
                    }
                    @Html.ActionLink("Modify", "Edit", new { id = Model.ProductID },
                             new { @class = "btn btn-default" })
                </div>

                <div class="well">

                    <div class="text-right">
                        @*<a class="btn btn-success">Leave a Review</a>*@
                        @Html.ActionLink("Leave a Review", "Create", 
                             "ProductReviews",
                             new { id = Model.ProductID },
                             new { @class = "btn btn-success" })
                    </div>

                    <hr>

                    @foreach(Catalog1.Models.ProductReview review
                        in Model.Reviews)
                    {
                        <div class="row">
                            <div class="col-md-12">
                                @for (int star = 0; star < 5; star++)
                                {
                                    if (star < review.Rating.Value)
                                    {
                                        <span class="glyphicon glyphicon-star"></span>
                                    }
                                    else
                                    {
                                        <span class="glyphicon glyphicon-star-empty"></span>
                                    }
                                }
                                @Html.DisplayFor(r => review.Title)
                                <span class="pull-right">@Html.DisplayFor(r => review.TimeStamp)</span>
                                <p>@Html.DisplayFor(r => review.ReviewText)</p>
                            </div>
                        </div>
                        <hr>
                    }

                </div>

            </div>

        </div>

    </div>
    <!-- /.container -->

    <div class="container">

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

Catalog1/Views/Product/DisplayStarRating.cshtml
@model Catalog1.Models.Product

@for (int star = 0; star < 5; star++)
{
    if (star < Model.AverageReview)
    {
        <span class="glyphicon glyphicon-star"></span>
    }
    else
    {
        <span class="glyphicon glyphicon-star-empty"></span>
    }
}

Catalog1/Views/Product/Edit.cshtml
@model Catalog1.Models.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderMaximumQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderMaximumQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderMaximumQuantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageSmall, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageSmall, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageSmall, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageLarge, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageLarge, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageLarge, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceModifier, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceModifier, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceModifier, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Catalog1/Views/Product/Purchase.cshtml
@{
    ViewBag.Title = "Purchase";
}

<h2>Thank you for your purchase!</h2>

Catalog1/Views/Product/ShoppingCart.cshtml
@model Catalog1.Models.Cart

@{
    ViewBag.Title = "ShoppingCart";
}

<h2>ShoppingCart</h2>

<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.Carts.First().Name)</th>
        <th>@Html.DisplayNameFor(model => model.Carts.First().Price)</th>
        <th>@Html.DisplayNameFor(model => model.Carts.First().Quantity)</th>
        <th>@Html.DisplayNameFor(model => model.Carts.First().SubTotal)</th>
    </tr>

    @foreach( Catalog1.Models.CartItem cartItem in Model.Carts )
    {
        
        <tr>
            <td>@cartItem.Name</td>
            <td>$@cartItem.Price</td>
            <td>@cartItem.Quantity</td>
            <td>@cartItem.SubTotal</td>
        </tr>
    }
</table>
<p>
    Total Price:
    $@Model.PriceTotal
</p>
@Html.ActionLink("Edit Shopping Cart", "Index", "CartItems", null,
    new { @class = "btn btn-default" })

@Html.ActionLink("Buy Now", "Purchase", null,
    new { @class = "btn btn-primary"})

Catalog1/Views/Product/index.cshtml
@model IEnumerable<Catalog1.Models.Product>

@{
    ViewBag.Title = "Welcome to our webstore, " + ViewBag.UserName;
}

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <div class="col-md-3">
                <p class="lead">Shop Name</p>
                <div class="list-group">
                    <a href="#" class="list-group-item">Category 1</a>
                    <a href="#" class="list-group-item">Category 2</a>
                    <a href="#" class="list-group-item">Category 3</a>
                </div>
            </div>

            <div class="col-md-9">

                <div class="row carousel-holder">

                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="item active">
                                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    </div>

                </div>
                
                <div class="row">
                    @foreach (Catalog1.Models.Product productItem in Model)
                    {
                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src="@productItem.ImageSmall" alt="">
                            <div class="caption">
                                <h4 class="pull-right">$@productItem.Price</h4>
                                <h4>
                                    @Html.ActionLink(productItem.Name, "Detail", new { id = productItem.ProductID })
                                </h4>
                                <p>@productItem.Description</p>
                            </div>
                            @Html.ActionLink("Details", "Detail", new { id = productItem.ProductID }, new { @class = "btn btn-default" })
                            <div class="ratings">
                                <p class="pull-right">@productItem.Reviews.Count() review(s)</p>
                                <p>
                                    @Html.Partial("DisplayStarRating", productItem)
                                </p>
                            </div>
                        </div>
                    </div>
                    }
                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <h4><a href="#">Like this template?</a>
                        </h4>
                        <p>If you like this template, then check out <a target="_blank" href="http://maxoffsky.com/code-blog/laravel-shop-tutorial-1-building-a-review-system/">this tutorial</a> on how to build a working review system for your online store!</p>
                        <a class="btn btn-primary" target="_blank" href="http://maxoffsky.com/code-blog/laravel-shop-tutorial-1-building-a-review-system/">View Tutorial</a>
                    </div>

                </div>

            </div>

        </div>

    </div>
    <!-- /.container -->

    <div class="container">

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery Version 1.11.0 -->
    @*<script src="js/jquery-1.11.0.js"></script>*@

    <!-- Bootstrap Core JavaScript -->
    @*<script src="js/bootstrap.min.js"></script>*@